import { TKeyManagerOptions } from './key-manager.types';

export type TModuleOptions = Partial<TKeyManagerOptions> & {
  quiet: boolean;
};

export enum EError {
  STORE_CONNECTION_ERROR = 'STORE_CONNECTION_ERROR',
  STORE_QUERY_ERROR = 'STORE_QUERY_ERROR',
  STORE_UPDATE_ERROR = 'STORE_UPDATE_ERROR',
  STORE_DELETE_ERROR = 'STORE_DELETE_ERROR',
  STORE_NOT_FOUND_ERROR = 'STORE_NOT_FOUND_ERROR',
  STORE_DUPLICATE_ERROR = 'STORE_DUPLICATE_ERROR',
  STORE_INVALID_DATA_ERROR = 'STORE_INVALID_DATA_ERROR',
  STORE_PERMISSION_ERROR = 'STORE_PERMISSION_ERROR',
  STORE_AUTH_ERROR = 'STORE_AUTH_ERROR',
  STORE_RATE_LIMIT_ERROR = 'STORE_RATE_LIMIT_ERROR',
  STORE_TIMEOUT_ERROR = 'STORE_TIMEOUT_ERROR',
  STORE_UNKNOWN_ERROR = 'STORE_UNKNOWN_ERROR',
}
